### ISSUE TITLE
Found false negatives

### ISSUE THREAD

**Issue by dschaehi** [ChenglongMa/zoplicate#37]
Hi @ChenglongMa,

Thanks again for the recent update, which removed all false positives in my case.
However, I found false negatives today, i.e., duplicates that are not shown in duplicate items (see the items in the attached Zotero RDF file).
Can you check whether this is specific to my setup or a general issue?

Best,
Jae

[Exported Items.rdf.zip](https://github.com/ChenglongMa/zoplicate/files/15219484/Exported.Items.rdf.zip)

**Comment by ChenglongMa** [comment]
Sure thing @dschaehi. I'll test it soon.

Thanks for your feedback!

**Comment by ChenglongMa** [comment]
Hi @dschaehi,

I think the most direct reason is that their DOI values ​​are different, which causes Zotero to no longer match other fields.

I'm not sure if it is common practice to treat the preprint version on Arxiv as equivalent to the published version. 

Any thoughts?

Thanks!

Best,
Chenglong

**Comment by dschaehi** [comment]
Hi @ChenglongMa,

I see. The thing is that often times I don't want to keep both versions and I discard the arXiv version as soon as I find a published version. There are few cases I want to keep both, because sometimes arXiv versions are more comprehensive than the published ones that are constrained by page limits. 
I wonder whether one can have options for both (i.e., allowing and disallowing such duplicates).

Best,
Jae

**Comment by ChenglongMa** [comment]
Hi @dschaehi,

I came across [this article](https://blog.arxiv.org/2022/02/17/new-arxiv-articles-are-now-automatically-assigned-dois/#:~:text=Will%20I%20still%20be%20able%20to%20provide%20an%20external%20DOI%20and/or%20journal%20reference%20with%20my%20article%3F).

Since January 2022, arXiv began assigning DOIs to the preprint papers. Authors are not only allowed but also encouraged to connect their papers with external DOIs. Thus, the impetus largely rests with the authors.

While developing a custom duplicate detection method appears to be the optimal solution, the current workaround may necessitate manual upkeep of these duplicates.

I will try my best to make the custom duplicate detection method available ASAP.

Thanks!

Best,
Chenglong

**Comment by dschaehi** [comment]
Thanks for the information, @ChenglongMa.
If there is no quick and elegant solution, then I'll wait for the new feature.

Best,
Jae
