### ISSUE TITLE
Some files cannot be merged, and the duplicate folder is not empty all the time

### ISSUE THREAD

**Issue by hasibagen** [ChenglongMa/zoplicate#48]
Zoplicatex shows duplicate files, and after merging the duplicate files, the previously displayed files are still there, and they are still there after refreshing, and they are still there after restarting Zotero.
Some files cannot be merged, and the duplicate folder is not empty all the time.
I am using Mac 13.6 (22G120), Zotero version 7.0.0-beta.81+721f54fe4, and Zoplicatex is the latest version of GitHub.

![Snipaste_2024-05-30_09-21-25](https://github.com/ChenglongMa/zoplicate/assets/12797356/469ba50b-b425-4dbb-9177-522426d59919)
![Snipaste_2024-05-30_09-23-23](https://github.com/ChenglongMa/zoplicate/assets/12797356/3ae39906-8427-44a0-bad0-b33071721a0e)

**Comment by ChenglongMa** [comment]
Hi @hasibagen,

Thanks for your feedback.

Based on the screenshot, it seems that the duplicates are in different item types, e.g., conference paper, book, web page.

The native merge function in zotero doesn't support merge items in different types, as suggested in the message pane.

I guess it's because they have different fields and cannot be merged automatically. For example, conference paper has DOI, but webpage doesn't have it.

If you have any good ideas to solve this issue, I'm very happy to implement it.

Thanks!

Best,
Chenglong

**Comment by hasibagen** [comment]
I want to ask if I can manually choose which one to keep?
In this interface, I cannot manually merge one by one, nor can I delete one of the articles.

**Comment by ChenglongMa** [comment]
I think you can do it in their collection pane or library. 

The duplicate pane is designed to select duplicate pairs automatically when clicking one item.

**Comment by ChenglongMa** [comment]
Hi, I will close this issue since it has been solved. Feel free to reopen it if you have other questions.

Thanks for your attention!
